server.port=8080
# ===============================
# CẤU HÌNH SITE 1 (WAREHOUSE - PORT 3308)
# ===============================
spring.datasource.site1.jdbc-url=jdbc:mysql://127.0.0.1:3308/warehouse_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.site1.username=root
spring.datasource.site1.password=rootpassword
spring.datasource.site1.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CẤU HÌNH SITE 2 (CUSTOMER - PORT 3307)
# ===============================
spring.datasource.site2.jdbc-url=jdbc:mysql://127.0.0.1:3307/customer_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.site2.username=root
spring.datasource.site2.password=rootpassword
spring.datasource.site2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=warn